// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/lecterkn/kaneki_bot/internal/app/client"
	"github.com/lecterkn/kaneki_bot/internal/app/handler"
	"github.com/lecterkn/kaneki_bot/internal/app/repository"
	"github.com/lecterkn/kaneki_bot/internal/app/usecase"
)

// Injectors from wire.go:

func InitializeHandlers() *HandlerSets {
	genaiClient := client.GetGeminiClient()
	generateRepository := repository.NewGenerateRepositoryImpl(genaiClient)
	generateUsecase := usecase.NewGenerateUsecase(generateRepository)
	messageHandler := handler.NewMessageHandler(generateUsecase)
	handlerSets := &HandlerSets{
		MessageHandler: messageHandler,
	}
	return handlerSets
}

// wire.go:

var clientSet = wire.NewSet(client.GetGeminiClient)

var repositorySet = wire.NewSet(repository.NewGenerateRepositoryImpl)

var usecaseSet = wire.NewSet(usecase.NewGenerateUsecase)

var handlerSet = wire.NewSet(handler.NewMessageHandler)

type HandlerSets struct {
	MessageHandler *handler.MessageHandler
}
