name: Build and Deploy Image
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # リポジトリにチェックアウト
      - name: checkout repository
        uses: actions/checkout@v4
      # イメージをビルド
      - name: build docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
      # dockerにログイン
      - name: login ghcr.io
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      # イメージをプッシュ
      - name: push image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
